# Generated by Django 5.1.5 on 2025-01-28 06:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_photo', models.ImageField(blank=True, upload_to='media/')),
                ('is_premium', models.BooleanField(default=False)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='media/')),
                ('square_foot', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=120)),
                ('bhk', models.CharField(choices=[('1', '1BHK'), ('2', '2BHK'), ('3', '3BHK'), ('4', '4BHK'), ('5', '5BHK')])),
                ('additional_bhk', models.CharField(blank=True, max_length=50, null=True)),
                ('open', models.BooleanField(default=True)),
                ('bought_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.account')),
            ],
        ),
    ]
