# Generated by Django 5.1.5 on 2025-01-28 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_properties_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bought_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.account'),
        ),
    ]
