# Generated by Django 5.1.5 on 2025-02-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_property_bought_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.FileField(upload_to='property/'),
        ),
    ]
